language: node_js

node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"

script:
  - npm install
  - npm test

cache:
  directories:
    - "node_modules"
